<a href="https://colab.research.google.com/github/2403A51L33/B52_PfDS/blob/main/Lab-03-05%20Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array([[1,2,3],
              [4,5,6]])
print("2D Array A:\n", A)
print("Shape of A:", A.shape)
b = np.array([10,20,30])
print("\n1D Array b:\n", b)
print("Shape of b:", b.shape)
C = A + b
print("\nA + b:\n", C)
print("Shape of result:", C.shape)
D = np.ones((2,3,4))
print("\n3D Array D shape:", D.shape)
E = D + 5
print("D + 5 shape:", E.shape)
f = np.array([1,2,3])
print("\nArray f:\n", f)
print("Shape of f:", f.shape)
f_new = f.reshape(1,3,1)
print("Reshaped f_new shape:", f_new.shape)
G = D + f_new
print("D + f_new shape:", G.shape)
try:
    X = np.ones((2,3))
    Y = np.ones((4,))
    Z = X + Y
except ValueError as e:
    print("\nInvalid Broadcasting Error:", e)

2D Array A:
 [[1 2 3]
 [4 5 6]]
Shape of A: (2, 3)

1D Array b:
 [10 20 30]
Shape of b: (3,)

A + b:
 [[11 22 33]
 [14 25 36]]
Shape of result: (2, 3)

3D Array D shape: (2, 3, 4)
D + 5 shape: (2, 3, 4)

Array f:
 [1 2 3]
Shape of f: (3,)
Reshaped f_new shape: (1, 3, 1)
D + f_new shape: (2, 3, 4)

Invalid Broadcasting Error: operands could not be broadcast together with shapes (2,3) (4,) 
